version: "3.8"
services: 
    db:
        image: mysql:latest
        restart: always
        command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
        volumes:
            - ./init.sql:/data/application/init.sql
            - ./mysql-data:/var/lib/mysql
        environment: 
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        ports: 
            - "3306:3306"
    app:
        restart: always
        depends_on:
            - db
        image: docker.pkg.github.com/associacao-de-programadores-depressivos/image-server/imageserver:latest
        environment:
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_NAME=${DB_NAME}
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - STORAGE_BUCKET_NAME=${STORAGE_BUCKET_NAME}
            - STORAGE_URL=${STORAGE_URL}
            - GOOGLE_SERVICE_ACCOUNT_PATH=${GOOGLE_SERVICE_ACCOUNT_PATH}
            - GOOGLE_SERVICE_ACCOUNT_CRED=${GOOGLE_SERVICE_ACCOUNT_CRED}
        ports: 
            - "8081:8081"